### ISSUE TITLE
Bug hunting

### ISSUE THREAD

**Issue by Kflash** [jiesa/jiesa#1]
All bugs found, list them in this thread. Jiesa are now in a optimization state, where bugs will be fixed as soon as they are found.

Jiesa should be stable enough by now to be used in production.

@jiesa/staff Any bugs to report?

**Comment by gaydenko** [comment]
I guess, `unmount()` must wait for all `destroy` hooks execution (if not, `destroy` callback parameter loses own sense). But with this code
```html
<html>
  <div id='id'></div>
  <script src="./jiesa/dist/jiesa.js"></script>
  <script>
    var tree = new jiesa.Tree();
    jiesa.initEvent();
    var mountId = null;

    var view = function() {
      return new jiesa.Element("button", {
        events: {
          click: function(ev) {
            console.log('will unmount');
            tree.unmount(mountId);
            console.log('unmounted');
          }
        },
        hooks: {
          destroy: function(el, next) {
            setTimeout(function() {
              console.log("calling next()");
              next();
              console.log("next() is called");
            }, 2000);
          }
        }
      }, [new jiesa.Text("Click me to unmount")]);
    }

    // mount element
    mountId = tree.mount(document.getElementById('id'), view);
  </script>
</html>
```
we can see in console `unmount` returns immediately. Console has got:
```txt
02:51:13.110 will unmount
02:51:13.112 unmounted
02:51:15.112 calling next() 
02:51:15.113 next() is called
```

**Comment by Kflash** [comment]
@gaydenko A `destroy hook` get executed in the same moment you click unmount. When you do a unmount, you remove current node from it's parent container. You destroy the tree. The hook get fired in the same moment. A similiar hook are the `detach` hook, that also detach / remove the child nodes. So the main purpose for the hook you mentioned are to get executed in the same moment you destroy the tree.

**Comment by gaydenko** [comment]
@Kflash , real DOM destroying take place on `next()` call only (that is button disappears after two seconds delay), and it is absolutely expected behavior. Now imagine, I want to unmount some node and then mount something else on the same place. Before mounting I'm forced to be sure all tasks in `destroy` hooks are completed. Yes, I can "invent" own system to track all `destroy` hooks completions, and to call `unmount` when all tasks are done. But I guess it would be natural for library to supply this expected behavior :) - that is return `unmount(mountId)` only when all `next()` in all destroy hooks related to `mountId` are completed.

**Comment by Kflash** [comment]
I will look into it soon as possible.

**Comment by Kflash** [comment]
@jiesa/staff Jiesa hooks now are identical to all other implementations as far as I know. Have you tried to run the `detach hook` first, and then the `destroy hook` ? A example are given in this spec:
https://github.com/jiesa/jiesa/blob/master/test/specs/hooks.spec.js#L58-L86

**Comment by gaydenko** [comment]
Let's use some definitions:

- "node level" - where we define node hooks
- "tree level" - where we call `mount()` and `unmount()`.

On the tree level (or, if you want, it can be called "component level", "module level", "page part level", or anything else) we know nothing about trees' internals supplied by registered `view()` function in `mountId = tree.mount(document.getElementById('id'), view)` call. On the tree level we just manipulate trees with `mount()` and `unmount()` - add to, remove from or replace in different mount points. 

At the last use case, that is when we replace tree in a given mount point, we need graceful termination of a tree (component) being removed before mounting another tree to the mount point. And recall, we are abstracted from those `view()` functions at the tree level, that is we know nothing about node level hooks.

This consideration is the reason I have suggested `unmount()` semantics, when it returns after all internal tree work is done (that is all `destroy()` hooks are completed).

I see, it can be impossible to implement this semantics directly, So, the issue can be resolved another softer way: let's add the second optional `unmount()` argument, and let's this argument be a callback function. If the argument is supplied: `tree.unmount(mountId, done)`, then `done()` is called when all `destroy()` hooks of the tree are completed.

This way Jiesa will be friendly with regard to embracing top level frameworks dealing with "components" or anything else you name :) Say, the `done()` callback can be easy integrated into (refactored to) asynchronous chain.

**Comment by Kflash** [comment]
@gaydenko I'm looking into this along my optimizing. During `unmount()`, no hooks are needed for this. When you do an `unmount()`, it will automaticly `detach()` all nodes. So for now, I added a `done()` callback for `unmount` as you suggested. This callback will not be triggered before all children are removed - `detached()`. 

You can see the code snippet here: https://github.com/jiesa/jiesa/blob/master/src/tree/prototype/unmount.js#L9-L32

**Comment by gaydenko** [comment]
I have tried a modified test case:
```js
<html>
  <div>Some static text</div>
  <div id='id'></div>
  <script src="./jiesa/dist/jiesa.js"></script>
  <script>
    var tree = new jiesa.Tree();
    jiesa.initEvent();
    var mountId = null;

    var view = function() {
      return new jiesa.Element("button", {
        events: {
          click: function(ev) {
            console.log('will unmount');
            tree.unmount(mountId, function() {
              console.log('unmounted');
            });
          }
        },
        hooks: {
          destroy: function(el, next) {
            setTimeout(function() {
              console.log("calling next()");
              next();
              console.log("next() is called");
            }, 1000);
          }
        }
      }, [new jiesa.Text("Click me to unmount")]);
    }

    // mount element
    mountId = tree.mount(document.getElementById('id'), view);
  </script>
</html>
```
But still get `unmounted` immediately, before `destroy()` termination.

**Comment by Kflash** [comment]
If you take a look at this spec, you will see that this `done()` callback get fired after all child nodes are detached when you do a unmount: https://github.com/jiesa/jiesa/blob/master/test/specs/mount.spec.js#L85-L94

Lets hope that help you a little until I can finish the rest. Now back to optimizing!

**Comment by gaydenko** [comment]
After clicking a button I get immediate `unmounted` on console when the button is still on the screen during 1000 ms.

**Comment by Kflash** [comment]
@gaydenko What method are you using now? If you use the done() callback, all children are gone. No need for hooks. As proven with a test spec as well. For the hooks, I will look into it soon optimizing are done.

**Comment by gaydenko** [comment]
@Kflash , I use an example listed above - just call console log inside `done()`, and it doesn't work both in FF and Chrome - I still get `unmounted` immediately, while a button still exists.

**Comment by gaydenko** [comment]
> `// the child nodes are gone, do something!!`
In the supplied use case a button still exists.

**Comment by gaydenko** [comment]
In other words, in given test case `done()` must be called after `next()`.

**Comment by Kflash** [comment]
I see what you mean. If you use done() as an replacement for your hook when you unmount - if the purpose is to get rid of all child nodes before mounting a new tree. This are working.
If you mix both hooks and done(), you will expierence the issue you see now.

The destroy() hook purpose are to remove all or a single child node of a mounted tree - same happen inside mount(). 

With  a delay as you are using, I would classify this as a wrong usecase if the purpose are what I described.

**Comment by gaydenko** [comment]
> With a delay as you are using, I would classify this as a wrong usecase if the purpose are what I described.

A use case can not be wrong - it is always valid as far as it is just a use case by definition :) 

The thing is, these days SPA can be heavy asynchronous, and not all decision with regard to work flow can be made immediately. Say, you want to unmount a component being a container for external API implementation (say, geo map service), and the API *demands* to call some cleanup before unmounting, or demands to load something before mounting... And so on. Of course, here we also have got all classical use cases in interaction with data server. 

So, I'd say, almost 100% of all component manipulation use cases in application in hands have got heavy asynchronous nature. It is just impossible to get application working without guaranteers `done()` is called after `next()`, if we return to the example.

**Comment by Kflash** [comment]
I understand your point. My idea with Jiesa was to have a low-level library - more or less a boilerplate - where such things could be added in a higher level of abstraction. And as a low-level library it's not a component framework :)

Just now I need to finish the things I need to do with Jiesa, after that I will fix all this things you mention. And I will turn Jiesa into a component framework with support for what you requestion. Give or take a 3 - 4 days before I'm done. I'm starting after optimizing.

**Comment by gaydenko** [comment]
@Kflash , I'm afraid, correct `done()` call supplying can influence overall library structure at noticeable degree, and it will result in needing reoptimization :)

**Comment by Kflash** [comment]
@gaydenko I tend to agree. It will be removed and replaced soon. Just now I'm thinking again...  It's not so easy the task I have in front of me.

**Comment by gaydenko** [comment]
> It's not so easy the task I have in front of me.

Yes, I must admit, it isn't simple. Hope, it is interesting at least :)

**Comment by Kflash** [comment]
Just to start with, I added a `createElement()` method for creating virtual elements. You can play around with that one, now back to optimizing.

**Comment by Kflash** [comment]
@gaydenko Just to make things clear. It's a component framework you want? I'm not a huge fan of frameworks like REACT, Deko, snabbDOM and the classics one, so it will not be like that.
Anyway. I'm done thinking :) What you requesting can be done easy if you wrap everything inside a container - component - and execute each hook, before calling the unmount.
Huge task this one - and I can't stick to 19KB size. But will fix soon after optimizing.

**Comment by gaydenko** [comment]
No-no! I don't want component framework at all! - and I hate this word "component" :) I want a visual layer library as Jiesa already is (event less as far as I'm not interested in server side rendering and probably few other features). To integrate the library with other SPA parts the library must fulfill few interaction game rules. No more!

**Comment by Kflash** [comment]
Ah ok! I sent you a private msg on Slack.
